### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by AuroraLS3** [Mirex97/Pelifoorumi#1]
Sisältö:
- Asennus
- Käyttökokemus
  - Testauskertomus
  - Heroku Testauskertomus
- Koodi
  - Ensivaikutelmat
  - Löydetyt ongelmat
  - Python tyyli-guidelinet
- Ehdotuksia
- Loppusanat
  
### Asennus

Repo ladattu 23.04. 9;53 commit 3c99d1419ef650b9ad72d77c7240cdb647687052  
Asennus onnistui ilman ongelmia requirements.txt tiedostosta Windows 10 koneella.
## Käyttökokemus

Olen lukenut dokumentaation ja tiedän että tyyli ei ole ollut vielä ensimmäinen prioriteetti, joten merkkaan kommenteihin tyylistä vain muistutuksena ja ehdotuksina. 

### Testauskertomus

Mitä | Kommentteja
-- | --
Rekisteröin uuden käyttäjän.
Katsoin 'Profile Information' | Tyyli puuttuu 
'MODIFY' | Tyyli puuttuu, laittaisin ehkä DELETE Account alimmaiseksi erilliseen osioon koska tämä lisää erotusta muusta muokkaus toiminnallisuudesta
Yritin vaihtaa käyttäjänimeä vaihtamatta salasanaa | Tämä ei onnistu koska salasana ja käyttäjänimi ovat samassa formissa. Osittaiset muutokset voisi tehdä erilaisilla "Onko tyhjä" tarkastuksilla
Menin 'Users' sivulle | Olen kirjautunut mutta koska en ole kirjoittanut mitään en ole aktiivinen käyttäjä. Kehotetaan silti rekisteröimään.
Painoin BreadCrumbs 'Index' | Foorumi on tyhjä ilman kehotuksia tehdä mitäänä
En voi luoda alueita koska olen 'default' |
En voi luoda viestejä koska ei ole alueita | 
En voi muuttaa itseäni adminiksi | 
En voi testata hakua koska ei ole viestejä |
Kirjauduin ulos |
Menin Users välilehdelle | Käyttäjä näkyy nyt, mikä on kummallista, kannattaa listata käyttäjä itse myös aktiivisiin käyttäjiin.

En jaksanut alkaa luomaan admin käyttäjää manuaalisesti joten menin herokuun

### Heroku Testauskertomus

Mitä | Kommentteja
-- | --
Index | Ilmeisesti ei vielä mitään laitettu ja siksi oli tyhjä
Menin News foorumille | Breadcumbs sanoo "Section", olisi ehkä mahdollista laittaa alueen nimi breadcrumbiin.
Yritin luoda threadin | Kirjautumis ikkuna 👍
Rekisteröin käyttäjän | Käyttäjä voi käyttää 1 merkin pituista salasanaa, mikä on mielestäni turvatonta.
Navigoin takaisin News foorumille ja kirjauduin sisään | Minut heitettiin index sivulle joten pitää navigoida 3. kerran.
Luon uuden langan "Kappas" | Langassa ei ole viestejä
Jätän tyhjän langan tänne ihan huvinvuoksi :) |
Luon uuden langan "Kappas2" ja yritän muuttaa sen tagia "Useless" | Tagit eivät ilmeisesti vielä toimi koska submit napin painamisen jälkeen tag muuttuu takaisin (kai?)
Yritän hakea lankaa tagilla "Useless" | 500 Internal error, KTS Koodi: Löydetyt Ongelmat models.py ongelma
Yritän hakea lankaa nimellä "kappas" | Ei löytynyt mitään, haku on "Case-sensitive". Useat käyttäjät eivät hae isoilla kirjaimilla.
Haen termillä "Kappas" | Molemmat löytyy
Menen lankaan "Stuff" | Voin näköjään poistaa toisten viestejä
Lähetän viestin | Viestit ovat uusin ensin, en tiedä onko se tarkoituksella
Yritän poistaa Kukkiksen viestin | Mitään ei tapahdu
Poistan oman viestin | Se toimii.

### Ensivaikutelmat

Koodi on hyvin rakennettu ja sitä on tuotettu paljon lyhyessä ajassa. Se on jaoiteltu paketteihin hyvin ja sitä on helppo lukea.

Näköjään `@app.routen` voi jakaa useampaan tiedostoon, hyvä tietää. - Itsellä se ei toiminut ja turvauduin [Blueprints](http://flask.pocoo.org/docs/0.12/blueprints/) toimintoon, jolla voi myös jakaa routet useampaan tiedostoon. Blueprints sallii myös URL:n eteen voi lisätä jonkin osan, esim "/section" jolloin routeen tulee "/" - Ei enää tässä vaiheessa kannata lähteä muuttamaan, mutta jos kiinnostaa niin tulevaisuuden projekteja ajatellen.

### Löydetyt ongelmat

Tiedosto | Rivi | Ongelma
-- | -- | --
tags/views.py | 36 | `render_tempalte` (kirjoitusvirhe)
sections/views.py | 68 | `request` ei importoitu
sections/views.py | 71 | `section_id` ei määritelty
tags/models.py | 21 | SQL lauseessa käytetty pöytien niminä `Thread`, `Account`, `Section`, `Tag`, `Tag_Thread` vaikka jokaisessa models.py tiedostossa on `__tablename__` joka on kirjoitettu pienellä kirjaimella.  Lisää selitystä alempana
Kaikki models.py tiedostot | - | Sama ongelma kuin yllä yhteenveto kyselyissä.
  |  |  
templates/auth/modify.html | 40 | `<table>` elementtiä ei suljettu
templates/auth/modify.html | 43 | `<form>` elementti sulkee `<p>` elementin koska se ei saa olla `<p>` elementin sisällä, suosittelen joko `<div style="display: inline;">` tai muuttamista GET metodiseksi `<a>` linkiksi
templates/auth/register.html | 40 | `<table>` elementtiä ei suljettu
templates/auth/view.html | 32 | `<table>` elementtiä ei suljettu
templates/theads/thead.html | 38 | `<li>` elementti ilman `<ul>` tai `<ol>` tagia
templates/layout.html | 41 | Kovakoodattu URL eikä url_for
templates/layout.html | 43 | (Minor) checkbox input tagille ei ole määritetty `<label for="tag"></label>` elementtiä
templates/layout.html | 44 | (Minor) checkbox input tagille ei ole määritetty `<label for="select"></label>` elementtiä
templates/layout.html | 71 | `</div>` ei sulje mitään elementtiä 

#### Miksi väärät taulun nimet toimivat testiympäristössä mutteivat Herokussa?

- SQLite tulkitsee taulujen nimet "case insensitive" ellei niiden ympärillä ole lainausmerkkejä esim `"Taulu"` ja PostgreSQL tulkitsee taulujen nimet "case sensitive". -> Aiheuttaa virheitä. Mikäli käyttää PyCharm Ultimatea voi asettaa testitietokannaksi SQLiten ja SQL Dialectiksi PostgreSQL jolloin syntax highlighting näyttää kyseiset virheet.

### Python Tyyli-guidelinet

Nämä ovat pikkuseikkoja, mutta kirjoitan ylös silti koska PyCharm niistä huomauttaa.

- Muutamassa paikassa on puolipilkkuja `;` joita ei yleensä käytetä (Löytyi 7)
- Ennen luokan alkua on kaksi tyhjää riviä
- Pää-importien jälkeen on kaksi tyhjää riviä

## Ehdotuksia

- Mikäli asennat [Flask-Bootstrap](https://pythonhosted.org/Flask-Bootstrap/index.html) kirjaston löytyy sieltä hyvä WTFormsia tukeva tyylitys apuri [linkki](https://pythonhosted.org/Flask-Bootstrap/forms.html)
- navigaation teksti on mustaa harmaalla. Vihreä tekstin väri varmaan korjaa asian.
- "Open Thread!" vaikuttaa status tyyliseltä ilmaukselta huutomerkin vuoksi, Sen voisi ehkä muuttaa napiksi tai laittaa linkin joko elementin onClick attribuuttiin tai langan nimeen
- Suosittelen haun laajentamista SQL muutoksella `LOWER(x) LIKE LOWER(?)`
- Poista napit on tehty formeilla koska halutaan käyttää POST metodia. Kannattaa lisätä `.btn` nappien tyyliin
- Kannattaa laajentaa tag toiminnallisuutta jotta tageja voi lisätä kuka tahansa ja langalla voi olla useampi kuin yksi tagi. Tagit voisi myös näyttää käyttäjille ´[Bootstrap badgeilla](https://getbootstrap.com/docs/4.0/components/badge/)
- Salasanat tallennetaan selkotekstinä, mikäli aikaa riittää suosittelen tutustumaan [bCrypt kirjastoon](https://pypi.org/project/bcrypt/3.1.0/) jolloin salasanat ovat turvassa mm. tietokantamurron yhteydessä.

## Loppusanat

Olet tehnyt hurjan määrän hommia. Html tiedostoja on suuri määrä joten niiden tyylittämisessä voi mennä aika kauan. Vaikka et alunperiin ollut käyttänyt pythonia on tiedostot jaettu hyvin osiin ja pakettieihin toimivasti. Virheitäkään ei ole kauheaa määrää ja ovat selitettävissä työkalujen puutteilla (Esim jos käytössä on ollut Netbeans tai vaikka Notepad++ tms). Toivon onnea ja menestystä opinnoissa.

Mikäli on kysymyksiä tai muuta tähän alle voi kommentoida niin vastaan kun kerkeän.

**Comment by Mirex97** [comment]
Unohdin tosiaan laittaa ohjeeksi kun käynnistää omalla koneella tämän projektin, että "Admin" rooli pitää antaa manuaalisesti käyttäjälle tietokannassa, jotta voi luoda noita osioita. Ajattelin sen olevan riski, jos on joku käyttäjä hard koodattuna sivulle, mutta testaamiseen se olisi ollut hyödyllinen :P. Onneksi herokussa olin heittänyt osioita, jotta pystyit testata noita kohtia.

Mutta hei kiitokset hyvästä palautteesta ja löydetyistä ongelmista! Ja eikun vain korjailemaan! 
+Kiitokset ehdotuksista!
T. Kukkis

PS. Erittäin hyvä huomio muuten tuo case sensitive, kun olen pitkään ihmetellyt tuota Herokun virhesanomia, kun avaa ensimmäisen kerran noita sivuja. Nyt sekin pitäisi ratketa!
